version: '2'
services:
  db:
    image: kartoza/postgis:9.5-2.2
    ports:
      - "25435:5432"
    env_file:
      - database.env

  geoserver:
    image: kartoza/geoserver:2.13.0
    ports:
      - "8600:8080"
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ${HOME}:/home/${USER}
    links:
      - db:db
  geogig:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.2.0
        BACKEND: DATABASE
      # Set $ADDR to your APT_CATCHER_IP where address can be found using
      # ADDR=`ifconfig wlan1 | grep 'indirizzo inet:' | cut -d: -f2 | awk '{ print $1}'`
        #APT_CATCHER_IP:$ADDR
    volumes:
      - ./data:/geogig_repo/gis
      - ${HOME}:/home/${USER}
    ports:
      - "38080:8182"
    env_file:
      - geogig.env
    depends_on:
      - db